DROP DATABASE IF EXISTS quizspiel;
CREATE DATABASE IF NOT EXISTS quizspiel;
USE quizspiel;

CREATE TABLE BENUTZER (
	USER_ID		INTEGER AUTO_INCREMENT NOT NULL,
	NAME		VARCHAR(255) NOT NULL,
	PASSWORT	VARCHAR(255) NOT NULL,
	PUNKTE		INTEGER NOT NULL,
	ADMIN		BOOL,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE KATEGORIEN (
	KAT_ID		INTEGER AUTO_INCREMENT NOT NULL,
	NAME		VARCHAR(20),
	PRIMARY KEY (KAT_ID)
);

CREATE TABLE FRAGEN (
	FRA_ID		INTEGER AUTO_INCREMENT NOT NULL,
	KAT_ID		INTEGER NOT NULL,
	FRAGE		VARCHAR(100),
	RICANT		VARCHAR(50),
	FALANT1		VARCHAR(50),
	FALANT2		VARCHAR(50),
	FALANT3		VARCHAR(50),
	PRIMARY KEY (FRA_ID),
	FOREIGN KEY (KAT_ID) REFERENCES KATEGORIEN (KAT_ID)
);