name: BrainBuster CI/CD Pipeline

on:
  push:
    branches:
      - FinalVersion
  pull_request:
    branches:
      - FinalVersion

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abh채ngigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code-Formatierung 체berpr체fen
        run: |
          pip install black
          black --check .

      - name: Tests ausf체hren
        run: |
          pip install pytest
          pytest tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/FinalVersion'
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Deployment simulieren
        run: echo "Deployment erfolgreich!"
